<a href="https://colab.research.google.com/github/yooshin2/Image-Processing/blob/main/NumpyPractice2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
array3 = np.concatenate([array1, array2], axis=0)
print(array3)

[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]


In [3]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = array1.reshape(2, 2)
print(array2)

[[1 2]
 [3 4]]


In [4]:
import numpy as np

array = np.random.randint(1, 10, size=4).reshape(2, 2)
result_array = array * 10

print(array)
print(result_array)

[[6 4]
 [1 6]]
[[60 40]
 [10 60]]


In [7]:
import numpy as np

array1 = np.arange(4).reshape(2, 2)
array2 = np.arange(2)
array3 = array1 + array2

print(array3)

[[0 2]
 [2 4]]


In [13]:
import numpy as np

array1 = np.arange(8).reshape(2, 4)
array2 = np.arange(8).reshape(2, 4)
array3 = np.concatenate([array1, array2], axis=0)
array4 = np.arange(4).reshape(4, 1)
array5 = array3 + array4

print(array5)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


In [18]:
import numpy as np

array1 = np.arange(16).reshape(4, 4)
print(array1)

print(array1 < 10)

array1[array1 < 10] = 100
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


In [25]:
import numpy as np

array = np.arange(4)

print("최댓값", np.max(array))
print("최솟값", np.min(array))
print("합계", np.sum(array))
print("평균", np.mean(array))

최댓값 3
최솟값 0
합계 6
평균 1.5


In [29]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print(array)

print("합계", np.sum(array, axis = 0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계 [24 28 32 36]


In [32]:
import numpy as np

array = np.arange(10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
import numpy as np

array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1 = array1, array2 = array2)

result = np.load('saved.npz')
result1 = result['array1']
result2 = result['array2']

print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [68]:
import numpy as np

array = np.array([7, 9, 10, 1, 4, 6])
array.sort()
print(array)

array = array[::-1]
print(array)

array = np.array([[5, 7, 1, 3, 6], [10, 8, 2, 6, 4]])
print(array)
array.sort(axis = 0)
print(array)

[ 1  4  6  7  9 10]
[10  9  7  6  4  1]
[[ 5  7  1  3  6]
 [10  8  2  6  4]]
[[ 5  7  1  3  4]
 [10  8  2  6  6]]


In [89]:
import numpy as np

array = np.linspace(0, 10, 5)
print(array)

np.random.seed(4)
print(np.random.randint(0, 10, (2, 3)))

array1 = np.arange(10)
array2 = array1
array2[0] = 99
print(array1)

array3 = np.arange(10)
array4 = array3.copy()
array4[3] =100
print(array3)

array5 = np.array([1, 3, 3, 5, 5, 1])
print(np.unique(array5))

[ 0.   2.5  5.   7.5 10. ]
[[7 5 1]
 [8 7 8]]
[99  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
[1 3 5]
