<a href="https://colab.research.google.com/github/yooshin2/Image-Processing/blob/main/NumpyPractice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

array = np.array([1, 2, 3])
print(array.size)
print(array.dtype)
print(array[1])

3
int64
2


In [26]:
import numpy as np

array1 = np.arange(4)
print(array1)

array2 = np.zeros((4, 4), dtype=int)
print(array2)

array3 = np.ones((4, 4), dtype=str)
print(array3)

array4 = np.random.randint(0, 10, (3,3))
print(array4)

array5 = np.random.normal(0, 1, (3, 3))
print(array5)

[0 1 2 3]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
[[5 6 7]
 [8 0 5]
 [8 8 2]]
[[-0.58797914 -1.19774589 -0.77732859]
 [-1.13409693 -0.97458446 -1.18357884]
 [ 0.25574265 -0.20361638 -0.28461536]]


In [37]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
array3 = np.concatenate([array1, array2])
print(array3)

[1 2 3 4 5 6]


In [34]:
import numpy as np

array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
array3 = np.concatenate([array1, array2], axis=0)
print(array3)

[[0 1 2 3]
 [0 1 2 3]
 [4 5 6 7]]
